import { HorizontalBox, Button, Palette } from "std-widgets.slint";
import { RustCallbacks } from "../globals.slint";

export component Footer inherits Rectangle {
    callback back <=> back.clicked;
    in property <bool> can_go_back: false;

    background: Palette.alternate-background;
    height: 76px;

    HorizontalLayout {
        property <length> size: parent.height - 2 * self.padding;

        alignment: stretch;
        padding: 16px;

        Rectangle {
            height: size;
            width: size;

            ta := TouchArea {
                clicked => RustCallbacks.open_settings();
            }

            Image {
                width: parent.width;
                height: parent.height;
                source: @image-url("../assets/settings.svg");
                rotation-angle: ta.has-hover ? 360deg : 0deg;
                animate rotation-angle { duration: 250ms; }
            }
        }

        Rectangle { }

        back := Button {
            text: "Back";
            height: size;
            width: 120px;
            enabled: can_go_back;
        }
    }
}
