import { BasePage } from "base-page.slint";
import { DiscordInstallAdapter, DiscordInstall } from "../globals.slint";
import { HorizontalBox, VerticalBox, Palette, ScrollView } from "std-widgets.slint";

component DiscordInstall inherits Rectangle {
    in property <DiscordInstall> install;
    property <brush> text_color;
    callback selected <=> touch.clicked;

    height: 8rem;
    border-radius: 8px;

    states [
        inactive when !touch.has-hover: {
            root.background: Palette.control-background;
            text_color: Palette.foreground;
        }
        active when touch.has-hover: {
            root.background: Palette.selection-background;
            text_color: Palette.selection-foreground;
        }
    ]

    animate background { duration: 100ms; }

    HorizontalBox {
        padding: 1rem;
        spacing: 20px;
        Image {
            horizontal-alignment: ImageHorizontalAlignment.left;
            source: DiscordInstallAdapter.branch_icon(install.branch);
            width: self.height;
        }

        VerticalBox {
            alignment: center;
            Text {
                text: DiscordInstallAdapter.branch_name(install.branch);
                font-size: 1.75rem;
                color: text_color;
                animate color { duration: 100ms; }
            }

            Text {
                text: install.folder-path;
                font-size: 1rem;
                opacity: 0.5;
                color: text_color;
                animate color { duration: 100ms; }
            }
        }
    }

    touch := TouchArea {
        width: 100%;
        height: 100%;
    }
}

export component InstallSelect inherits BasePage {
    title: "Select Discord Installation";

    VerticalLayout {
        spacing: 20px;
        padding-left: 20px;
        padding-right: 20px;

        for discord in DiscordInstallAdapter.installs: DiscordInstall {
            install: discord;
            selected => {
                DiscordInstallAdapter.selected_install = discord;
                root.next();
            };
        }
    }
}
