import { VerticalBox, StyleMetrics } from "std-widgets.slint";
import { Footer } from "footer.slint";

export component BasePage inherits VerticalBox {
    in property <string> title;
    in property <bool> can_go_back: false;
    callback next;
    callback back <=> footer.back;

    padding: 0;
    padding-top: 1rem;
    alignment: space-between;
    spacing: 1rem;

    Text {
        text: title;
        font-size: 2.5rem;
        horizontal-alignment: center;
    }

    @children

    footer := Footer {
        can_go_back: root.can_go_back;
    }
}
