export enum DiscordBranch {
    Stable,
    PTB,
    Canary,
}

export struct DiscordInstall {
    branch: DiscordBranch,
    folder_path: string,
}

export global DiscordInstallAdapter {
    in property <[DiscordInstall]> installs;
    in property <DiscordInstall> selected_install;

    public pure function branch_name(branch: DiscordBranch) -> string {
        if (branch == DiscordBranch.Stable) {
            return "Stable";
        } else if (branch == DiscordBranch.PTB) {
            return "PTB";
        } else if (branch == DiscordBranch.Canary) {
            return "Canary";
        }
        return "";
    }

    public pure function branch_icon(branch: DiscordBranch) -> image {
        if (branch == DiscordBranch.Stable) {
            return @image-url("assets/stable.svg");
        } else if (branch == DiscordBranch.PTB) {
            return @image-url("assets/ptb.svg");
        } else if (branch == DiscordBranch.Canary) {
            return @image-url("assets/canary.svg");
        }
        return @image-url("assets/stable.svg");
    }
}

export global RustCallbacks {
    pure callback open_settings;
}
