import { StandardButton, Button, VerticalBox, HorizontalBox } from "std-widgets.slint";

export component SettingsDialog inherits Dialog {
    title: "Settings";
    preferred-width: 800px;

    VerticalLayout {
        Text {
            text: "This is a dialog box";
        }
    }

    StandardButton {
        kind: ok;
    }

    StandardButton {
        kind: apply;
    }

    StandardButton {
        kind: cancel;
    }
}
